package com.bsoft.news_repository

import android.os.Parcelable.Creator

data class Article(
    val article_id: String,
    val category: List<String>,
    val country: List<String>,
    val creator: List<String>?,
    val description: String,
    val image_url: String?,
    val keywords: List<String>?,
    val language: String,
    val link: String,
    val pubDate: String,
    val pubDateTZ: String,
    val source_icon: String,
    val source_id: String,
    val source_name: String,
    val source_priority: Int,
    val source_url: String,
    val title: String
)

data class ArticleResponse(
    val status: String,
    val totalResults: Int,
    val results: List<Article>,
    val nextPage: String
)

val SampleArticleResponse = ArticleResponse(
    status = "success",
    totalResults = 4316,
    nextPage = "1738736619365884621",
    results = listOf(
        Article(
            article_id = "cb6e096dfccb87b7fda1beea54a39a2e",
            title = "Motorists to pay N500, N1,600 on Abuja-Keffi-Akwanga-Makurdi highway",
            link = "https://dailytrust.com/motorists-to-pay-n500-n1600-on-abuja-keffi-akwanga-makurdi-highway/",
            keywords = listOf( "news", "motorists", "abuja-keffi-akwanga-makurdi highway"),
            creator = listOf("Faruk Shuaibu"),
            description = "The federal government has disclosed that motorists plying the Abuja-Keffi-Akwanga-Makurdi Highway will now pay tolls ranging from N500 for saloon cars to N1,600 for multi-axle vehicles. The Minister of Works, Sen. David Umahi, said during the official inauguration of the new tolling regime at Garaku Toll Station, Nasarawa State, that funds generated from the venture [...]",
            pubDate = "2025-02-05 06:27:15",
            pubDateTZ=  "UTC",
            image_url = "https://dailytrust.com/wp-content/uploads/2025/02/motorists-to-pay-n500-n1600-on-abuja-keffi-akwanga-makurdi-highway.jpg",
            source_id = "dailytrust",
            source_priority = 57151,
            source_name = "Daily Trust",
            source_url = "https://dailytrust.com",
            source_icon = "https://i.bytvi.com/domain_icons/dailytrust.png",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id = "66470f979dca62794090f4b49f09c2cb",
            title = "Ododo Appeals Ohinoyi Of Ebiraland’s Sacking",
            link = "https://newtelegraphng.com/ododo-appeals-ohinoyi-of-ebiralands-sacking/",
            keywords = listOf("news"),
            creator = listOf("Muhammad Bashir"),
            description = "The Kogi State Government yesterday against a Lokoja High Court’s removal of the Ohinoyi of Ebiraland, Tijani Ahmed-Anaje on Monday. The Attorney General of the state Muzi Abdullahi said the state government filed the appeal at the Court of Appeal Abuja. Justice Umar Salisu in his judgment on the case filed by Daudu AdekuOjiah, Hussain...The post Ododo Appeals Ohinoyi Of Ebiraland’s Sacking appeared first on New Telegraph.",
            pubDate = "2025-02-05 06:26:27",
            pubDateTZ = "UTC",
            image_url = "https://i0.wp.com/newtelegraphng.com/wp-content/uploads/2025/02/images-30-2.jpeg?fit=739%2C415&ssl=1",
            source_id = "newtelegraphng",
            source_priority = 447614,
            source_name = "New Telegraph",
            source_url = "https://newtelegraphng.com",
            source_icon = "https://i.bytvi.com/domain_icons/newtelegraphng.png",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id = "d2e5582e8e6b291f7e5260cbcb64a6da",
            title = "EPL: How Al Nassr’s Boniface snub blocked Arsenal from signing Watkins in January window",
            link = "https://dailypost.ng/2025/02/05/epl-how-al-nassrs-boniface-snub-blocked-arsenal-from-signing-watkins-in-january-window/",
            keywords = listOf("sport", "arsenal", "epl", "watkins", "boniface"),
            creator = listOf("Ifreke Inyang"),
            description = "Arsenal would have stood a better chance of signing Ollie Watkins from Aston Villa if Al Nassr moved ahead with their plan to sign Victor Boniface from Bayer Leverkusen in the January window. The Gunners failed to add a single player to their squad in the winter market. After losing both Bukayo Saka and Gabriel [...]EPL: How Al Nassr’s Boniface snub blocked Arsenal from signing Watkins in January window",
            pubDate = "2025-02-05 06:26:05",
            pubDateTZ = "UTC",
            image_url = "https://dailypost.ng/wp-content/uploads/2025/02/MixCollage-05-Feb-2025-07-24-AM-6934.jpg",
            source_id = "dailypost",
            source_priority = 55306,
            source_name = "Daily Post",
            source_url = "https://dailypost.ng",
            source_icon = "https://i.bytvi.com/domain_icons/dailypost.jpg",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id =  "d90f9fe9e3c97f19e9e4233146e644ff",
            title = "Re-open Sapele Polytechnic abandoned 15 years ago, host communities appeal to Delta govt",
            link = "https://tribuneonlineng.com/re-open-sapele-polytechnic-abandoned-15-years-ago-host-communities-appeal-to-delta-govt/",
            keywords = listOf("host communities", "delta govt", "niger delta"),
            creator = listOf("Alphonsus Agborh"),
            description = "Tribune OnlineRe-open Sapele Polytechnic abandoned 15 years ago, host communities appeal to Delta govtAfter 15 years of abandonment, host communities have appealed to the Delta State government to reopen the Sapele Polytechnic, Deghele-Iriabome in Sapele Local Government Area of the state. The institution was among the four Polytechnics established in 2010 by former Governor Dr. Emmanuel Uduaghan though construction commenced in 2012 at the permanent site at the [...]Re-open Sapele Polytechnic abandoned 15 years ago, host communities appeal to Delta govtTribune Online",
            pubDate = "2025-02-05 06:25:40",
            pubDateTZ = "UTC",
            image_url = null,
            source_id = "tribuneonlineng",
            source_priority = 84500,
            source_name = "Tribune",
            source_url = "https://tribuneonlineng.com",
            source_icon = "https://i.bytvi.com/domain_icons/tribuneonlineng.png",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id = "b375ab2e7025232cae6f3adda28334b0",
            title= "A night of honour as Governor Yusuf celebrates 35 Kano indigenes for exceptional service",
            link = "https://blueprint.ng/a-night-of-honour-as-governor-yusuf-celebrates-35-kano-indigenes-for-exceptional-service/",
            keywords = listOf("kano", "features"),
            creator = listOf("Samson Benjamin"),
            description = "In the first of its kind, the Kano state government took time out to celebrate its accomplished indigenes across all human endeavours. SUNUSI BATURE DAWAKIN TOFA writes In a grand ... The post A night of honour as Governor Yusuf celebrates 35 Kano indigenes for exceptional service appeared first on Blueprint Newspapers Limited.",
            pubDate = "2025-02-05 06:25:28",
            pubDateTZ = "UTC",
            image_url = "https://blueprint.ng/wp-content/uploads/2025/02/images.jpg",
            source_id = "blueprint",
            source_priority = 917110,
            source_name = "Blueprint Newspapers",
            source_url = "https://blueprint.ng/feed",
            source_icon = "https://i.bytvi.com/domain_icons/blueprint.jpg",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id = "9381c62961fc619a1e86c85839607559",
            title = "NERC releases new power tariff hike guidelines for DisCos",
            link = "https://businessday.ng/uncategorized/article/nerc-releases-new-power-tariff-hike-guidelines-for-discos/",
            keywords = listOf("bdrecent", "uncategorized", "bd recent", "electricity tariffs", "nigerian electricity regulatory commission (nerc)"),
            description = "NERC (Nigeria’s electricity regulator) has released new rules about how electricity prices will be changed, as people are concerned aboutread more NERC releases new power tariff hike guidelines for DisCos",
            pubDate = "2025-02-05 06:24:36",
            pubDateTZ = "UTC",
            creator = listOf("Oluwatosin Ogunjuyigbe"),
            image_url = "https://cdn.businessday.ng/2017/11/NERC-renews-generation-licence-for-Afam-VI-power-plant-for-another-10-years.jpg",
            source_id = "businessday",
            source_priority = 92206,
            source_name = "Business News Nigeria",
            source_url = "https://businessday.ng",
            source_icon = "https://i.bytvi.com/domain_icons/businessday.jpg",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id = "c46cbc4224ba441e20d325c10e283d9d",
            title = "ISOX Shipping Offers Fast and Affordable Global Shipping & Logistics Services to Nigeria",
            link = "https://punchng.com/isox-shipping-offers-fast-and-affordable-global-shipping-logistics-services-to-nigeria/",
            keywords = listOf("sponsored"),
            creator = listOf("Branded Content"),
            description = "ISOX SHIPPING (est. 2012) is a one-stop logistics solution provider that offers a variety of logistics solutions for importing and exporting goods within Nigeria, the United States of America, the United Kingdom, Canada, China, India, Dubai, South Africa, Hong Kong, Singapore, Holland, Germany, Italy, France, Ireland, and other countries. We have a global network in Read More",
            pubDate = "2025-02-05 06:24:22",
            pubDateTZ = "UTC",
            image_url = "https://cdn.punchng.com/wp-content/uploads/2025/02/05082513/sox.jpg",
            source_id = "punchng",
            source_priority = 19103,
            source_name = "Punch",
            source_url = "https://punchng.com",
            source_icon = "https://i.bytvi.com/domain_icons/punchng.jpg",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id = "b3735a472cf0c2abeddc3647b98d2770",
            title = "ISOX Shipping:Fast and Affordable Global Shipping&Logistics Services to Nigeria",
            link = "https://punchng.com/isox-shippingfast-and-affordable-global-shippinglogistics-services-to-nigeria/",
            keywords = listOf("sponsored"),
            creator = listOf("Branded Content"),
            description = "ISOX SHIPPING (est. 2012) is a one-stop logistics solution provider that offers a variety of logistics solutions for importing and exporting goods within Nigeria, the United States of America, the United Kingdom, Canada, China, India, Dubai, South Africa, Hong Kong, Singapore, Holland, Germany, Italy, France, Ireland, and other countries. We have a global network in Read More",
            pubDate = "2025-02-05 06:24:22",
            pubDateTZ = "UTC",
            image_url = "https://cdn.punchng.com/wp-content/uploads/2025/02/05082513/sox.jpg",
            source_id = "punchng",
            source_priority = 19103,
            source_name = "Punch",
            source_url = "https://punchng.com",
            source_icon = "https://i.bytvi.com/domain_icons/punchng.jpg",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id = "6ada1a7ba14f9c19b13db0c478a4099b",
            title = "NIMC approves FIC to participate in the ID4D project",
            link = "https://www.vanguardngr.com/2025/02/nimc-approves-fic-to-participate-in-the-id4d-project/",
            keywords = listOf("news"),
            creator = null,
            description = "The management of the National Identity Management Commission (NIMC) has approved the participation of FIC Professionals Network Plc in the Identity for Development (ID4D) Ecosystem Enrolment Service. A recognised stakeholder owned organisation and key player in the financial inclusion ecosystem which recently partnered with the Chartered Institute of Bankers of Nigeria (CIBN) to introduce the [...]The post NIMC approves FIC to participate in the ID4D project appeared first on Vanguard News.",
            pubDate = "2025-02-05 06:23:53",
            pubDateTZ = "UTC",
            image_url = null,
            source_id = "vanguardngr",
            source_priority = 13294,
            source_name = "Vanguard News",
            source_url = "https://www.vanguardngr.com",
            source_icon = "https://i.bytvi.com/domain_icons/vanguardngr.png",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
        Article(
            article_id = "b51eefdf2068c748c8cfcfa94c9d6961",
            title = "Court Frees Fani-Kayode Of Medical Forgery",
            link = "https://newtelegraphng.com/court-frees-fani-kayode-of-medical-forgery/",
            keywords = listOf("news"),
            creator = listOf("Francis Iwuchukwu"),
            description = "Justice Olubunmi Abike-Fadipe of an Ikeja Special Offences Court yesterday acquitted and discharged former Minister of Aviation Femi Fani-Kayode of charges of medical forgery filed against him by the Economic and Financial Crimes Commission (EFCC). The judge arrived at the decision while ruling on the ‘no case submission’ filed by Fani-Kayode’s counsel, Wale Balogun (SAN)....The post Court Frees Fani-Kayode Of Medical Forgery appeared first on New Telegraph.",
            pubDate = "2025-02-05 06:23:39",
            pubDateTZ = "UTC",
            image_url = "https://i0.wp.com/newtelegraphng.com/wp-content/uploads/2025/02/images-29-2.jpeg?fit=650%2C350&ssl=1",
            source_id = "newtelegraphng",
            source_priority = 447614,
            source_name = "New Telegraph",
            source_url = "https://newtelegraphng.com",
            source_icon = "https://i.bytvi.com/domain_icons/newtelegraphng.png",
            language = "english",
            country = listOf("nigeria"),
            category = listOf("top"),
        ),
    )
)